[2024-01-25T14:04:35.236+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: your_dag_id.use_yaml_data_task manual__2024-01-25T14:04:33.827090+00:00 [queued]>
[2024-01-25T14:04:35.242+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: your_dag_id.use_yaml_data_task manual__2024-01-25T14:04:33.827090+00:00 [queued]>
[2024-01-25T14:04:35.243+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-25T14:04:35.255+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): use_yaml_data_task> on 2024-01-25 14:04:33.827090+00:00
[2024-01-25T14:04:35.260+0000] {standard_task_runner.py:60} INFO - Started process 438 to run task
[2024-01-25T14:04:35.262+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'your_dag_id', 'use_yaml_data_task', 'manual__2024-01-25T14:04:33.827090+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/test_pipeline_dag.py', '--cfg-path', '/tmp/tmp_y304u5x']
[2024-01-25T14:04:35.263+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask use_yaml_data_task
[2024-01-25T14:04:35.297+0000] {task_command.py:423} INFO - Running <TaskInstance: your_dag_id.use_yaml_data_task manual__2024-01-25T14:04:33.827090+00:00 [running]> on host cb568e1e9ab6
[2024-01-25T14:04:35.351+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='your_dag_id' AIRFLOW_CTX_TASK_ID='use_yaml_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-25T14:04:33.827090+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-25T14:04:33.827090+00:00'
[2024-01-25T14:04:35.360+0000] {logging_mixin.py:188} INFO - {'id': 'CVE-2022-20705', 'info': {'name': 'CVE-2022-20705', 'author': 'Lennaert89', 'severity': 'critical', 'description': 'Multiple vulnerabilities in Cisco Small Business RV160, RV260,\nRV340, and RV345 Series Routers could allow an attacker to do any of the\nfollowing: Execute arbitrary code, Elevate privileges, Execute arbitrary commands,\nBypass authentication and authorization protections, Fetch and run unsigned\nsoftware, Cause denial of service (DoS). For more information about these\nvulnerabilities, see the Details section of this advisory.\n', 'reference': ['https://cve.mitre.org/cgi-bin/cvename.cgi?name=2022-20705']}, 'classification': {'cvss-metrics': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H', 'cvss-score': 9.8, 'cve-id': 'CVE-2022-20705', 'cwe-id': 'CWE-787', 'tags': ['cve', 'cve2022', 'cve-2022-20705', 'cisco']}, 'requests': [{'method': 'GET', 'path': ['{{baseURL}}/upload'], 'headers': {'Cookie': 'sessionid=../../www/index.html; sessionid={{rand_text_alphanumeric(16)}}'}, 'matchers-condition': 'or', 'matchers': [{'type': 'status', 'status': [405]}]}]}
[2024-01-25T14:04:35.361+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-25T14:04:35.369+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=your_dag_id, task_id=use_yaml_data_task, execution_date=20240125T140433, start_date=20240125T140435, end_date=20240125T140435
[2024-01-25T14:04:35.394+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-25T14:04:35.408+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
